### ISSUE TITLE
PALEOsediment roadmap

### ISSUE THREAD

**Issue by sjdaines** [PALEOtoolkit/PALEOsediment.jl#5]
TODO list for PALEO sediment reaction-transport models:

- [x] Add phosphorus mineralogy (iron-bound phosphorus and CFA formation), eg Slomp (1996) https://dx.doi.org/10.1357/0022240963213745, Zhao (2020) https://dx.doi.org/10.1038/s41467-020-15673-3, Dale (2016) https://dx.doi.org/10.1016/j.gca.2016.05.046
- [ ] Generalize isotope support (currently have a minimal example with S isotopes in SO4 and H2S, needs extending to Fe-S chemistry and to other isotope systems)
- [x] Add multi-G / reactive-continuum organic carbon eg Dale (2015) https://dx.doi.org/10.1002/2014GB005017
- [x] Aqueous carbonate system and minerals (should be just a case of configuring PALEO water column carbonate chemistry)
